# 2个必填配置选项
site_name: Beni Docs
site_url: https://pytask.com
copyright: 粤ICP备17090505号

docs_dir: source # 源文件（.md）路径
site_dir: docs # 生成文件（.html/.css/...）路径

theme:
  name: material
  favicon: img/favicon.svg
  logo: img/favicon.svg
  language: zh
  custom_dir: custom_theme
  features:
    - content.tabs.link
    - content.code.annotate
    - navigation.top
    - navigation.tracking
    # - navigation.instant # 异步加载
    # - navigation.indexes # 不清楚
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: purple
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<benimang@126.com>
      # name: 联系邮箱 benimang@126.com
#   generator: false # 屏蔽底部（Made with Material for MkDocs）

plugins:
  - search:
      lang: zh

markdown_extensions:
  - meta
  - abbr
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: ⚓︎
      toc_depth: 6
      slugify: !!python/name:pymdownx.slugs.uslugify_cased
  - pymdownx.highlight:
      use_pygments: true
      # auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 欢迎光临: index.md
  - 网站建设:
      - website/setup.md
      - website/writing.md
  - backup:
      - Index: bak/index.md
      - About: bak/about.md
