title: Lorem ipsum dolor sit amet
description: Nullam urna elit, malesuada eget finibus ut, ac tortor.
# 2个必填配置选项
site_name: Beni Docs
site_url: https://pytask.com

docs_dir: source # 源文件（.md）路径
site_dir: docs # 生成文件（.html/.css/...）路径

theme:
  name: material
  favicon: img/favicon.svg
  logo: img/favicon.svg
  lang: zh
  features:
    - content.tabs.link
    - content.code.annotate
    - navigation.top
    # - navigation.instant # 异步加载
    # - navigation.indexes # 不清楚
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: purple
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<benimang@126.com>
      # name: 联系邮箱 benimang@126.com
#   generator: false

copyright: 粤ICP备17090505号

markdown_extensions:
  - meta
  - pymdownx.highlight:
      use_pygments: true
      # auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: ⚓︎
      toc_depth: 6
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - index.md
  - xxxx:
      - about.md
      - xxxx2:
          - about2.md
