# 2个必填配置选项
site_name: Beni Docs
site_url: https://pytask.com

docs_dir: source # 源文件（.md）路径
site_dir: docs # 生成文件（.html/.css/...）路径

theme:
  name: material
  favicon: img/favicon.svg
  logo: img/favicon.svg
  lang: zh
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: purple
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/medium
      link: mailto:benimang@126.com
      name: 联系邮箱 benimang@126.com
#   generator: false

copyright: 粤ICP备17090505号

markdown_extensions:
  - toc:
      permalink: "#"

nav:
  - Homexx: index.md
  - About: about.md
