# 2个必填配置选项
site_name: Beni Docs
site_url: https://pytask.com

docs_dir: source # 源文件（.md）路径
site_dir: docs # 生成文件（.html/.css/...）路径

theme:
  name: material
  favicon: img/favicon.svg
  logo: img/favicon.svg

markdown_extensions:
  - toc:
      permalink: "#"

nav:
  - Homexx: index.md
  - About: about.md